timezone: "Australia/Melbourne"
data_config: true

collections_config:
  calendar:
    path: content/calendar
  community:
    path:content/community
  events:
    path: content/events
    output: true
    parser: yaml
    schemas:
      default:
        path: schemas/event.md
  forms:
    path: content/forms
  learning:
    path: content/learning
  news:
    path: content/news
  newsletters:
    path: content/newsletters
  our-school:
    path: content/our-school
  policies:
    path: content/policies
  publications:
    path: content/publications
  updates:
    path: content/updates
    output: true
    parser: yaml
    schemas:
      default:
        path: schemas/update.md
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
