timezone: "Australia/Melbourne"
data_config: true

collections_config:
  updates:
    path: content/updates
    icon: event
    description: Latest school updates.
    schemas:
      default:
        path: schemas/update.md
  calendar:
    path: content/calendar
    icon: event 
    description: School calendar.
  community:
    path: content/community
    icon: event
    description: Community section of the website.
  events:
    path: content/events
    icon: event
    description: Upcoming school events.
    schemas:
      default:
        path: schemas/event.md
  forms:
    path: content/forms
    icon: event
    description: School forms.
  learning:
    path: content/learning
    icon: event
    description: Learning section of the website.
  newsletters:
    path: content/newsletters
    icon: event
    description: Unused newsletter section of the website.
  our-school:
    path: content/our-school
    icon: event
    description: Our school section of the website.
  policies:
    path: content/policies
    icon: event
    description: Policies section of the website.
  publications:
    path: content/publications
    icon: event
    description: Publications section of the website.
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
