timezone: "Australia/Melbourne"
data_config: true

collections_config:
  events:
    schemas:
      default:
        path: schemas/event.md
  news:
    schemas:
      default:
        path: schemas/new.md
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
