timezone: "Australia/Melbourne"
data_config: true

collections_config:
  calendar:
    path: content/calendar
    icon: calendar_month
    description: School calendar.
  community:
    path: content/community
    icon: article 
    description: Community section of the website.
  events:
    path: content/events
    icon: today 
    description: Upcoming school events.
    text_key: title
    subtext_key: summary
    schemas:
      default:
        path: schemas/event.md
  forms:
    path: content/forms
    icon: list
    description: School forms.
  learning:
    path: content/learning
    icon: article 
    description: Learning section of the website.
  newsletters:
    path: content/newsletters
    icon: library_books
    description: Unused newsletter section of the website.
  our-school:
    path: content/our-school
    icon: article
    description: Our school section of the website.
  pages:
    _enabled_editors:
      - visual
      - content
      - data
  policies:
    path: content/policies
    icon: policy 
    description: Policies section of the website.
  publications:
    path: content/publications
    icon: menu_book 
    description: Publications section of the website.
  updates:
    path: content/updates
    icon: newspaper
    description: Latest school updates.
    text_key: title
    subtext_key: summary
    add_options:
      - name: Add update
        editor: content
    schemas:
      default:
        path: schemas/update.md
_structures:
  menu:
    values:
      - label: 'Item'
        value: 
          name: ""
          link: ""
      - label: 'Nest'
        value: 
          title: ""
          menu: ""
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
  draft:
    type: switch 
  banner:
    type: image

_snippets:
  image:
    template: hugo_shortcode_positional_args
    inline: false
    preview:
      text: Image
    definitions:
      shortcode_name: image
      positional_args:
        - editor_key: image
          type: string 
        - editor_key: image_name
          type: string 
      _inputs:
        image:
          type: image
        image_name:
          type: text 
