timezone: "Australia/Melbourne"
data_config: true

collections_config:
  events:
    path: content/events
    output: true
    parser: yaml
    schemas:
      default:
        path: schemas/event.md
  news:
    path: content/news
    output: true
    parser: yaml
    schemas:
      default:
        path: schemas/new.md
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
