timezone: "Australia/Melbourne"
data_config: true

collections_config:
  calendar:
    path: content/calendar
    icon: calendar_month
    description: School calendar.
  community:
    path: content/community
    icon: article 
    description: Community section of the website.
  events:
    path: content/events
    icon: today 
    description: Upcoming school events.
    text_key: title
    subtext_key: summary
    schemas:
      default:
        path: schemas/event.md
  forms:
    path: content/forms
    icon: list
    description: School forms.
  learning:
    path: content/learning
    icon: article 
    description: Learning section of the website.
  newsletters:
    path: content/newsletters
    icon: library_books
    description: Unused newsletter section of the website.
  our-school:
    path: content/our-school
    icon: article
    description: Our school section of the website.
  pages:
    _enabled_editors:
      - visual
      - content
      - data
  policies:
    path: content/policies
    icon: policy 
    description: Policies section of the website.
  publications:
    path: content/publications
    icon: menu_book 
    description: Publications section of the website.
  updates:
    path: content/updates
    icon: newspaper
    description: Latest school updates.
    text_key: title
    subtext_key: summary
    add_options:
      - name: Add update
        editor: content
    schemas:
      default:
        path: schemas/update.md
_structures:
  menu:
    values:
      - label: 'Item'
        value: 
          name: ""
          link: ""
      - label: 'Nest'
        value: 
          title: ""
          menu: ""
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
  draft:
    type: switch 
  banner:
    type: image

_snippets:
  image_1:
    template: hugo_shortcode_named_args
    inline: false
    preview:
      text:
        - key: alt_text
        - Image
      subtext:
        - key: caption
        - Full-width image with an optional caption below.
      gallery:
        image:
          - key: src
        text: No preview available
        fit: contain
      icon: image
      image: src
      view: gallery
    definitions:
      shortcode_name: image_1
      named_args:
        - editor_key: src 
          type: string 
        - editor_key: alt 
          type: string
        - editor_key: caption
          type: string
    _inputs:
      src:
        type: image
      alt:
        type: text 
      caption:
        type: text

  image_2:
    template: hugo_shortcode_named_args
    inline: false
    preview:
      image: 
        - key: src_1
        - Image missing
      text:
        - key: alt_1
        - First image
    definitions:
      shortcode_name: image_2
      named_args:
        - editor_key: src_1 
          type: string 
        - editor_key: alt_1
          type: string
        - editor_key: caption_1
          type: string
        - editor_key: src_2
          type: string 
        - editor_key: alt_2
          type: string
        - editor_key: caption_2
          type: string
    _inputs:
      src_1:
        type: image
      alt_1:
        type: text 
      caption_1:
        type: text
      src_2:
        type: image
      alt_2:
        type: text 
      caption_2:
        type: text