timezone: "Australia/Melbourne"
data_config: true

collections_config:
  events:
    path: content/events
    output: true
    parser: yaml
    schemas:
      default:
        path: schemas/event.md
  updates:
    path: content/updates
    output: true
    parser: yaml
    schemas:
      default:
        path: schemas/update.md
_inputs:
  summary:
    type: markdown
  content:
    type: markdown
  icon_svg:
    type: textarea
