baseURL = "https://andersonscreekps.vic.edu.au"
buildFuture = true
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-AU"
paginate = 5
paginatePath = ""
theme = "acps"
timeout = "300000"
title = "Andersons Creek Primary School"
uglyURLs = false
metaDataFormat = "toml"
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
[params]
DateForm = "2.1.2006"
address = "36-42 Drysdale Rd, Warrandyte VIC 3113"
cloudinary_base_url = "https://res.cloudinary.com/andersonscreekps"
front_page_transforms = "q_60,f_auto,e_sharpen"
image_transforms = "q_60,f_auto,e_sharpen"
upload_image_transforms = "upload/q_60,f_auto,e_sharpen"
email = "andersons.creek.ps@education.vic.gov.au"
mapLink = "https://goo.gl/maps/bt97uRvLDCz2U5Yd8"
name = "Andersons Creek Primary School"
phone = "03 9844 2757"
banner = "/banners/20211021-081453-default.jpg"
[permalinks]
forms = "/forms/:title/"
news = "/news/:year/:month/:day/:title/"
policies = "/policies/:title/"
reports = "/reports/:title/"

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'
