baseURL = "https://www.andersonscreekps.org/"
buildFuture = true
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-AU"
paginate = 5
paginatePath = ""
theme = "acps"
timeout = "300000"
title = "Andersonʼs Creek Primary School"
uglyURLs = false
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[[menu.main]]
name = "Forms"
parent = "Our school"
weight = 6
[[menu.main]]
name = "Policies"
parent = "Our school"
weight = 5
[[menu.main]]
name = "School calendar"
parent = "Events"
weight = 2
[[menu.main]]
name = "News"
pre = "newspaper"
weight = 5
[[menu.main]]
name = "Events"
pre = "calendar-alt"
weight = 4
[[menu.main]]
name = "Community"
pre = "users"
weight = 3
[[menu.main]]
name = "Learning"
pre = "user-graduate"
weight = 2
[[menu.main]]
name = "Our school"
pre = "info-circle"
weight = 1
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
[params]
DateForm = "2.1.2006"
address = "36-42 Drysdale Rd, Warrandyte VIC 3113"
cloudinary_base_url = "https://res.cloudinary.com/andersonscreekps"
description = "Anderson’s Creek Primary School is situated 30 kms northeast of Melbourne at Warrandyte, adjacent to Anderson's Creek. We have a school population of 350 students."
email = "andersons.creek.ps@edumail.vic.gov.au"
mapLink = "https://goo.gl/maps/ze1F3q9gQP82"
name = "Anderson’s Creek Primary School"
phone = "03 9844 2757"
[permalinks]
events = "/events/:year/:month/:day/:title/"
news = "/news/:year/:month/:day/:title/"
