title = "Andersonʼs Creek Primary School"
baseURL = "https://www.andersonscreekps.org/"
languageCode = "en-AU"
theme = "acps"
uglyURLs = true 
disableHugoGeneratorInject = true
#disableKinds options  ["page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
disableKinds = ["taxonomy", "taxonomyTerm"]
timeout = "300000"
disableAliases = true

[permalinks]
  events = "/events/:year/:month/:title/"
  news = "/news/:year/:month/:title/"

[outputs]
  home = ["HTML", "RSS", "REDIRECTS"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
  [outputFormats.REDIRECTS]
    mediatype = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[params]
  cloudinary_base_url = "https://res.cloudinary.com/gqdmtaegmix3/image/upload"
  name = "Anderson’s Creek Primary School"
  description ="Anderson’s Creek Primary School is situated 30 kms northeast of Melbourne at Warrandyte, adjacent to Anderson's Creek. We have a school population of 350 students."
  phone = "03 9844 2757"
  email = "andersons.creek.ps@edumail.vic.gov.au"
  address = "36-42 Drysdale Rd, Warrandyte VIC 3113"
  DateForm = "2.1.2006"
