baseURL = "https://www.andersonscreekps.org/"
buildFuture = true
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-AU"
paginate = 5
paginatePath = ""
theme = "acps"
timeout = "300000"
title = "Andersons Creek Primary School"
uglyURLs = false
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[[menu.main]]
name = "Our school"
pre = "info-circle"
weight = 1
[[menu.main]]
name = "Learning"
pre = "user-graduate"
weight = 2
[[menu.main]]
name = "Community"
pre = "users"
weight = 3
[[menu.main]]
name = "Events"
pre = "calendar-alt"
weight = 4
[[menu.main]]
name = "News"
pre = "newspaper"
weight = 5
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
[params]
DateForm = "2.1.2006"
address = "36-42 Drysdale Rd, Warrandyte VIC 3113"
cloudinary_base_url = "https://res.cloudinary.com/andersonscreekps"
front_page_transforms = "q_60,f_auto,e_sharpen"
image_transforms = "q_60,f_auto,e_sharpen"
description = "Andersons Creek Primary School is situated 30 kms northeast of Melbourne at Warrandyte, adjacent to Andersons Creek."
email = "andersons.creek.ps@education.vic.gov.au"
mapLink = "https://goo.gl/maps/bt97uRvLDCz2U5Yd8"
name = "Andersons Creek Primary School"
phone = "03 9844 2757"
[permalinks]
forms = "/forms/:title/"
news = "/news/:year/:month/:day/:title/"
policies = "/policies/:title/"
reports = "/reports/:title/"
