title = "Andersonʼs Creek Primary School"
baseURL = "https://www.andersonscreekps.org/"
languageCode = "en-AU"
theme = "acps"
uglyURLs = false
disableHugoGeneratorInject = true
#disableKinds options  ["page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
timeout = "300000"
disableAliases = true
buildFuture = true
paginate = 5
paginatePath = ""

[permalinks]
  events = "/events/:year/:month/:day/:title/"
  news = "/news/:year/:month/:day/:title/"

[outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
  [outputFormats.REDIRECTS]
    mediatype = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[menu]
  [[menu.main]]
    pre = "info-circle"
    name = "Our school"
    weight = 10

  [[menu.main]]
    pre = "user-graduate"
    name = "Learning"
    weight = 20

  [[menu.main]]
    pre = "users"
    name = "Community"
    weight = 30

  [[menu.main]]
    pre = "calendar-alt"
    name = "Events"
    weight = 40

  [[menu.main]]
    pre = "newspaper"
    name = "News"
    weight = 50

[params]
  cloudinary_base_url = "https://res.cloudinary.com/andersonscreekps"
  name = "Anderson’s Creek Primary School"
  description ="Anderson’s Creek Primary School is situated 30 kms northeast of Melbourne at Warrandyte, adjacent to Anderson's Creek. We have a school population of 350 students."
  phone = "03 9844 2757"
  email = "andersons.creek.ps@edumail.vic.gov.au"
  address = "36-42 Drysdale Rd, Warrandyte VIC 3113"
  mapLink = "https://goo.gl/maps/ze1F3q9gQP82"
  DateForm = "2.1.2006"

