[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.88.1"
  TZ = "Australia/Melbourne"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
