[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.52"

[context.production.environment]
  HUGO_VERSION = "0.52"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.52"
