---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Home
  create: all
  match: "*"
- type: directory
  path: content/our-school
  label: Our school
  create: all
  match: "**/*"
- type: directory
  path: content/learning
  label: Learning
  create: all
  match: "**/*"
- type: directory
  path: content/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/calendar
  label: Calendar
  create: all
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
  templates:
  - news
- type: directory
  path: content/newsletters
  label: Newsletters
  create: all
  match: "**/*"
  templates:
  - newsletter
- type: directory
  path: content/policies
  label: Policies
  create: all
  match: "**/*"
  templates:
  - policy
- type: directory
  path: content/forms
  label: Forms
  create: all
  match: "**/*"
  templates:
  - form
- type: directory
  path: content/publications
  label: Publications
  create: all
  match: "**/*"
  templates:
  - publication
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
