---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Home
  create: all
  match: "*"
- type: directory
  path: content/our-school
  label: Our school
  create: all
  match: "**/*"
- type: directory
  path: content/learning
  label: Learning
  create: all
  match: "**/*"
- type: directory
  path: content/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/newsletters
  label: Newsletters
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.52'
