---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Home
  create: all
  match: "*"
- type: directory
  path: content/our-school
  label: Our school
  create: all
  match: "**/*"
- type: directory
  path: content/learning
  label: Learning
  create: all
  match: "**/*"
- type: directory
  path: content/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
  templates:
  - news
- type: directory
  path: content/newsletters
  label: Newsletters
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
